# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

stages:
  - test

install_dependencies:
  stage: test
  script:
    - cd backend
    - pip install pytest
    - pip install -r requirements.txt
  artifacts:
    expire_in: 1 hour
    paths:
      - .venv/

run_tests:
  stage: test
  script:
    - cd backend
    - coverage run -m pytest tests/test_main,py
    - coverage xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/tests/coverage.xml
