version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cache:/var/cache/nginx/proxy_temp
    depends_on:
      - backend
      - frontend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "80:80"
