version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cache:/var/cache/nginx/proxy_temp
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=coin_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - ./backend:/app
    depends_on:
      - db


volumes:
  db_data:
    external: false